"""
Headless Blender script. Reads a Mixamo FBX (e.g. X Bot.fbx) and writes a
Python module containing the canonical Mixamo skeleton:
    - bone names
    - parent indices
    - rest offsets (parent->child head, in armature local space, meters)
    - rest matrices (3x3, bone -> armature space, at rest)

The output module is consumed by export_bvh.py to write a Mixamo-native BVH
(matching names + measurements) without requiring Blender at export time.

Usage:
    blender --background --python extract_mixamo_template.py -- \
        --fbx "C:/path/X Bot.fbx" --out tools/retarget/mixamo_template.py
"""

import bpy
import sys
import os
import argparse


def parse_args():
    argv = sys.argv
    argv = argv[argv.index("--") + 1:] if "--" in argv else []
    p = argparse.ArgumentParser()
    p.add_argument("--fbx", required=True)
    p.add_argument("--out", required=True)
    return p.parse_args(argv)


def clean_scene():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete()


def find_armature():
    for obj in bpy.data.objects:
        if obj.type == "ARMATURE":
            return obj
    return None


def main():
    args = parse_args()
    clean_scene()
    bpy.ops.import_scene.fbx(filepath=args.fbx)
    arm = find_armature()
    if arm is None:
        print("ERROR: no armature in FBX")
        sys.exit(1)

    bones = list(arm.data.bones)
    name_to_idx = {b.name: i for i, b in enumerate(bones)}

    entries = []
    arm_scale = arm.scale[0]  # Mixamo objects have scale 0.01 typically
    for i, b in enumerate(bones):
        parent_idx = name_to_idx[b.parent.name] if b.parent else -1
        head = b.head_local  # in armature local space
        if b.parent:
            offset = head - b.parent.head_local
        else:
            offset = head
        # bone.matrix_local: rest matrix in armature space
        m = b.matrix_local.to_3x3()
        rest = [list(m[r]) for r in range(3)]
        entries.append({
            "name": b.name,
            "parent": parent_idx,
            "offset": [offset.x * arm_scale, offset.y * arm_scale, offset.z * arm_scale],
            "rest_world_3x3": rest,
        })

    out_path = os.path.abspath(args.out)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write('"""Auto-generated by extract_mixamo_template.py — do not edit manually."""\n\n')
        f.write("MIXAMO_BONES = [\n")
        for e in entries:
            f.write("    {\n")
            f.write(f"        'name': {e['name']!r},\n")
            f.write(f"        'parent': {e['parent']},\n")
            ox, oy, oz = e['offset']
            f.write(f"        'offset': ({ox:.6f}, {oy:.6f}, {oz:.6f}),\n")
            r = e['rest_world_3x3']
            f.write("        'rest_world_3x3': (\n")
            for row in r:
                f.write(f"            ({row[0]:.6f}, {row[1]:.6f}, {row[2]:.6f}),\n")
            f.write("        ),\n")
            f.write("    },\n")
        f.write("]\n")

    print(f"Wrote {len(entries)} bones to {out_path}")


if __name__ == "__main__":
    main()
